### ISSUE TITLE
Package id changed

### ISSUE THREAD

**Issue by ghost** [SpEcHiDe/WhatsAppTransmitter#2]
You changed the package id. This makes this a completely new app with no way to upgrade existing users.

**Comment by SpEcHiDe** [comment]
I had created the earlier package id when I had the domain http://btappnder.freeiz.com/ but now that domain is gone, and also I made some improvements, which are:
the files are no longer stored on the server. 
only the base64 encoded string is stored.
so, no need to make the server 777.

How do you suggest that the package id to be changed?

**Comment by ghost** [comment]
Wether or not a domain is yours or not should be irrelevant for package id. Once chosen, you stick with it...

...sigh: If you still intend to change it, here is the problem: The update an app Android checks at least three things.

1) Is the package id the same?
2) Is it signed by the same key?
3) Is the versioncode higher than what is already installed?

So the user will have to install the new one and remove the old one, no way around that. The only thing you can do is explain it to the users. E.g. you could add a check on startup what package id the app has, if its still the old, display a dialog that explains the situation. We than can easily build the app twice (with the old and with the new id), so existing users get one last updated that shows the information.

**Comment by SpEcHiDe** [comment]
I do not think anybody has installed the previous version of the application, except me.
Even if somebody has installed it, the application would have been useless, since the files would not be uploaded to the server and would show a consistent error.
I do not want the old package id.

**Comment by ghost** [comment]
Ok, https://gitlab.com/fdroid/fdroiddata/commit/4dd7272f0d9c745fbf5d5c0bec56a255581006e0 should address this. Closing.
